swagger: '2.0'
info:
  title: API Title
  version: '1.0'
host: api.e-wallet.test
basePath: /
schemes:
  - https
paths:
  /user/login:
    post:
      description: ''
      parameters:
        - in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/user_login_request'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/user_login_response'
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
  /cart/add:
    post:
      description: 'Add products to cart'
      parameters:
        - in: header
          name: Authorization
          require: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjZlNWM0NC1iZmU4LTQ0MmUtYjQ4MC1jYTZhY2Q3MGNiNmQifQ.b1keCpvW7OgohPWiI5O3UliejohFV2GKWTwFBVgfKR8"
        - in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/add_to_cart_request'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/cart'
        '403':
          description: Forbidden
        '400':
          description: Bad Request
  /cart/checkout:
    post:
      description: 'Checkout cart, convert cart to order'
      parameters:
        - in: header
          name: Authorization
          require: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjZlNWM0NC1iZmU4LTQ0MmUtYjQ4MC1jYTZhY2Q3MGNiNmQifQ.b1keCpvW7OgohPWiI5O3UliejohFV2GKWTwFBVgfKR8"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/order'
        '403':
          description: Forbidden
        '400':
          description: Bad Request
  /cart-item/{cart_item_id}/changeqty:
    put:
      description: 'Add products to cart'
      parameters:
        - in: header
          name: Authorization
          require: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjZlNWM0NC1iZmU4LTQ0MmUtYjQ4MC1jYTZhY2Q3MGNiNmQifQ.b1keCpvW7OgohPWiI5O3UliejohFV2GKWTwFBVgfKR8"
        - in: path
          name: cart_item_id
          description: Cart Item Id
        - in: body
          name: payload
          required: true
          schema:
            type: object
            properties:
              quantity:
                type: integer
                example: 3
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/cart'
        '403':
          description: Forbidden
        '400':
          description: Bad Request
  /cart-item/{cart_item_id}:
    delete:
      description: 'Remove a cart item'
      parameters:
        - in: header
          name: Authorization
          require: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjZlNWM0NC1iZmU4LTQ0MmUtYjQ4MC1jYTZhY2Q3MGNiNmQifQ.b1keCpvW7OgohPWiI5O3UliejohFV2GKWTwFBVgfKR8"
        - in: path
          name: cart_item_id
          description: Cart Item Id
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/cart'
        '403':
          description: Forbidden
        '400':
          description: Bad Request
definitions:
  user:
    type: object
    properties:
      userId:
        type: string
        format: $uuid
        example: c6d05f62-50cc-4c67-b6f8-21a170ee09db
      username:
        type: string
      password:
        type: string
  product:
    type: object
    properties:
      product_id:
        type: string
        format: $uuid
        example: 518e8af7-6617-42a3-a227-b9be1b70fec8
      name:
        type: string
        example: iPhone 13 Pro Max 128GB
      price:
        type: number
        example: 29190000
  cart_item:
    type: object
    properties:
      cart_item_id:
        type: string
        format: $uuid
      product_id:
        type: string
        format: $uuid
        example: 518e8af7-6617-42a3-a227-b9be1b70fec8
      quantity:
        type: integer
        example: 3
      subtotal_ex_tax:
        type: number
        description: subtotalExTax = itemPrice * quantity
      tax_total:
        type: number
        description: tax = contentsTotal * 10%
      total:
        type: number
        description: Subtotal = contentsTotal + taxTotal
  cart:
    type: object
    properties:
      cart_id:
        type: string
        format: $uuid
      userId:
        type: string
        format: $uuid
        description: In a time an user has 0..1 cart
      cart_items:
        type: array
        items:
          $ref: '#/definitions/cart_item'
      subtotal_ex_tax:
        type: number
      tax_total:
        type: number
      total:
        type: number
  order_item:
    type: object
    properties:
      order_item_id:
        type: string
        format: $uuid
      product_id:
        type: string
        format: $uuid
        example: 518e8af7-6617-42a3-a227-b9be1b70fec8
      quantity:
        type: integer
        example: 3
      subtotal_ex_tax:
        type: number
        description: subtotalExTax = itemPrice * quantity
      tax_total:
        type: number
        description: tax = contentsTotal * 10%
      total:
        type: number
        description: Subtotal = contentsTotal + taxTotal
  order:
    type: object
    properties:
      order_id:
        type: string
        format: $uuid
      userId:
        type: string
        format: $uuid
        description: In a time an user has 0..1 cart
      cart_items:
        type: array
        items:
          $ref: '#/definitions/order_item'
      subtotal_ex_tax:
        type: number
      tax_total:
        type: number
      total:
        type: number
      payment_status:
        type: string
  user_login_request:
    type: object
    properties:
      username:
        type: string
        example: username
      password:
        type: string
        example: Abcd1234@
  user_login_response:
    type: object
    properties:
      token:
        type: string
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZjZlNWM0NC1iZmU4LTQ0MmUtYjQ4MC1jYTZhY2Q3MGNiNmQifQ.b1keCpvW7OgohPWiI5O3UliejohFV2GKWTwFBVgfKR8
  add_to_cart_request:
    type: object
    properties:
      productId:
        type: string
        format: $uuid
        example: 518e8af7-6617-42a3-a227-b9be1b70fec8
      quantity:
        type: integer